### ISSUE TITLE
/full entries for theories

### ISSUE THREAD

**Issue by DianaHajTPS** [BeautifulTrouble/BeautifulRisingBot#49]
@phillipadsmith It seems like the command /full for theories doesn't work for a reason or another

![screen shot 2016-12-01 at 1 28 00 pm](https://cloud.githubusercontent.com/assets/9722200/20806723/0729a7a4-b7ca-11e6-9a71-523ef1b3d26d.png)

**Comment by phillipadsmith** [comment]
> @phillipadsmith It seems like the command /full for theories doesn't work for a reason or another

Thank you for the report. Investigating...

**Comment by phillipadsmith** [comment]
Ah-ha! Okay, I've found an issue. I'll work on fix.

**Comment by phillipadsmith** [comment]
Fixed.
